### ISSUE TITLE
Vulkan support uses latest spec which causes Vulkan-Hpp to fail compilation

### ISSUE THREAD

**Issue by wesleygriffin** [mosra/flextgl#17]
I've put a MWE here: https://github.com/wesleygriffin/flextgl_repro

I'm using CMake to use the flextgl Vulkan loader with the Vulkan-Hpp bindings and the latest released LunarG SDK (1.1.73).

The installed vulkan.hpp file static_assert's on VK_HEADER_VERSION == 73.

This assert fails because flextgl is grabbing the latest xml spec from https://raw.githubusercontent.com/KhronosGroup/Vulkan-Headers/master/registry/vk.xml which sets VK_HEADER_VERSION to 75.

I tried looking at the Vulkan-Hpp repo, but they've already updated the generated header there to 76.

I'd like to be able to specify "version 1.1.73" in the profile and then have flextgl use that version of the spec.

Issues I see:
  1. The Vulkan-Headers repo doesn't tag the various version commits
  2. The vk.xml spec file is not bundled with the LunarG SDK.

Thanks,
Wes

**Comment by mosra** [comment]
Hi! I am not sure if trying to pick up old versions of the `vk.xml` file is a good idea (the past versions of the xml file *might* have bugs that were fixed soon after but didn't result in a version bump etc.). Most importantly, the *first ever* version in the Vulkan-Headers repo is 1.1.74, so it's not even possible to get older versions from there, one has to look elsewhere.

I see three possibilities here:

- report a bug to Vulkan-Hpp, ask them to either remove this assert, make it at least `>=` (because, if the spec was correctly designed, newer headers should be a superset of the old headers, *not* breaking compatibility), or wrap parts of their code with `#if VK_HEADER_VERSION >= something`
- use vulkan.hpp from upstream and ignore the one from the SDK
- manually download an older `vk.xml` file and put it in the `spec/` directory. [Here is the one for 1.1.73.](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/097b0f5acbb5a50dfb2ccdbaa48e7cc8f08ed94d/scripts/vk.xml) If the file modification date is fresh enough, `flextGLgen.py` won't attempt to redownload a new copy and just uses the one that's there.

I dare to say the first option is the best (in my opinion having such a strict dependency on a particular *revision* (not even a version) does more harm than good), while the third could be the easiest for you right now.

**Comment by wesleygriffin** [comment]
Vulkan-Hpp has stated they must tie to a specific patch version: https://github.com/KhronosGroup/Vulkan-Hpp/issues/108

I'll use the upstream vulkan.hpp.

Thanks,
Wes

**Comment by mosra** [comment]
Hi again, completely by accident I stumbled upon a repo wich actually *does have* all the versions tagged and everything: https://github.com/KhronosGroup/Vulkan-Docs

So there you go: since dfbf63cc892c078f11da51666c6b879f2c977ed0 it's possible to request a particular release and the script will download and use exactly that version. 

The layout of that repository and the tagging scheme changed significantly in the past, so this works only back to version 1.1.72. I hope it settled down already and will stay like this in the future, though :)

**Comment by wesleygriffin** [comment]
Oh wow, that's awesome - thank you so much!
