### ISSUE TITLE
Add vkEnumerateInstanceVersion to list of statically loadable functions

### ISSUE THREAD

**Issue by wesleygriffin** [mosra/flextgl#18]
Based on my reading here: https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#initialization-functionpointers

I think you can add vkEnumerateInstanceVersion to the list of functions that can be statically loaded. I don't have a PR but I could probably put one together if that would help.

My limited testing was taking the generated flextVk.* files, manually changing vkEnumerateInstanceVersion to a statically defined function and then calling it, which did work. This is on the 1.1.82.1 SDK release.

Thanks,
Wes

**Comment by mosra** [comment]
Hi! :)

I faintly remember reading about this function in the 1.1 changelog and being quite angry about it. The function is new in 1.1 and if I would load it statically, the header would no longer link with drivers that expose only Vulkan 1.0 (I assume there is at least one Android vendor that is still stuck on 1.0, for example).

The [LunarG changelog for 1.1](https://vulkan.lunarg.com/doc/view/1.1.70.0/linux/tutorial/html/16-vulkan_1_1_changes.html) mentions that and in order to "make your app more versatile" (scroll down to that chapter), they suggest to still load it using `vkGetInstanceProcAddress()` and not statically.

I think the right way to go here would be to create a new `flextVkInitStatic()` function which only purpose would be to load function pointer for `vkEnumerateInstanceVersion()`. Then the client code has to check if the function pointer is non-null in order to call it. What do you think?

EDIT: what about calling them `flextVkInit()` (for the static version) and `flextVkInitInstance()` (for the per-instance pointers)? Looks more consistent to me.

**Comment by wesleygriffin** [comment]
I'm wondering if we can expect additional functions to get added down the road that don't require an instance (adding lines to Table 1 in the spec where instance is NULL). My actual work-around right now is:
~~~
  // Force the loading of vkEnumerageInstanceVersion to use it prior to
  // instance creation
  flextvkEnumerateInstanceVersion =
    reinterpret_cast<VkResult(VKAPI_PTR*)(uint32_t*)>(
      vkGetInstanceProcAddr(VK_NULL_HANDLE, "vkEnumerateInstanceVersion"));
~~~
which isn't too far from calling `flextVkInitStatic()`

But if more functions get added like this, then I would definitely prefer just a single call to initialize all the static functions and thus you're back to having effectively a global `flextVkInit()` function.

I'll leave the decision up to you, right now I'm fine just manually loading the address.

**Comment by mosra** [comment]
> I'm wondering if we can expect

I think there definitely will be more of them in the future, yes.

> I would definitely prefer just a single call to initialize all the static functions

I just implemented this in the `next` branch, in particular 9b0ca16cb26188f45d08d8b5eff4741f2d060dc7. Can you quickly look at it and test if it does the right thing? If yes, then I'll merge this to master. Thank you!

**Comment by wesleygriffin** [comment]
That commit works for me. I'm not calling `flextVkInit()` and then `vkEnumerateInstanceVersion()` before creating an instance and calling `flextVkInitInstance()`

Thanks!

**Comment by mosra** [comment]
Awesome. Pushed to `master` now, closing as resolved.

> I'm not calling `flextVkInit()`

Surely you meant *now*, right? :)

**Comment by wesleygriffin** [comment]
Yes, sorry, I did mean _now_ calling :)
