### ISSUE TITLE
flextVK expects statically linking to vulkan

### ISSUE THREAD

**Issue by to-miz** [mosra/flextgl#19]
In contrast to vulkan.hpp, which loads everything dynamically, the generated loaders from the vulkan templates still need one to statically link to vulkan.
I can circumvent this by defining vkCreateInstance myself and using eg LoadLibraryW and GetProcAddress on Windows, but that seems backwards. The rationale seems to be to "avoid the need for a global flextVkInit()", but at some point flextVkInit was introduced anyway.

Loading everything dynamically would have these benefits from my point of view:
- Being able to fallback to another API if vulkan is not available, or display a more meaningful error message.
- The consumer of the generated loader doesn't have to change his linker settings and can use them as is.
- Header-only libraries that want to include a subset of vulkan using this generator don't need users to link against vulkan.

**Comment by mosra** [comment]
Hi! Yeah, sure :)

The good thing about this library is that it's just a matter of the particular template you use. Do you perhaps have a modification to the [default vulkan one](https://github.com/mosra/flextgl/tree/master/templates/vulkan) that's doing dynamic loading? Or can you borrow such code from some other (compatibly-licensed) project that does have that? (volk, vulkan.hpp...)

In my projects ([Magnum](https://github.com/mosra/magnum) etc.) I link to Vulkan statically and even have a custom template to match their requirements, so I have unfortunately nothing I could reuse here.

**Comment by to-miz** [comment]
I have modified templates with code borrowed from vulkan.hpp, see https://github.com/to-miz/flextgl/tree/94d5136c3c7658506a572e566328240b9b1a2800 under templates/vulkan_dyn

Should I open a pull request? Although I don't know how to properly credit/mark the code I borrowed from vulkan.hpp, I just included the copyright notice which has a licensing option for MIT.

**Comment by mosra** [comment]
> Should I open a pull request?

Yes, that would be great, thank you. Couple comments:

- can you rename the template to `vulkan-dynamic` instead of `vulkan_dyn`? 
- instead of referencing `vkGetInstanceProcAddr` through a `#define`, can you directly use `flextvkGetInstanceProcAddr`? So it doesn't depend on the defines in the header, which people might want to remove.
- can you list the template in the README among other templates and briefly explain why people would want to use it?
- the licensing looks okay I think, to be sure it would be good to mention that in the Credits section of the README as well (and feel free to add yourself there too ;))

**Comment by mosra** [comment]
Fixed by #20 and merged as b5ca501c95bd168dcbf972219a6050223de49984. Thanks!
